version: "3.7"
services:
  # Snapshot hub
  snapshot-hub:
    build: ../../thirdparty/snapshot-hub
    container_name: snapshot-hub
    env_file:
      - ../../.env
    environment:
      JAWSDB_URL: postgres://admin:admin@snapshot-postgres:5432/snapshot-db
    depends_on:
      - snapshot-postgres
    ports:
      - 8080:8080
  # Snapshot Postgres instance
  snapshot-postgres:
    image: bitnami/postgresql:13
    container_name: snapshot-postgres
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: "admin"
      POSTGRESQL_DATABASE: snapshot-db
    ports:
      - 5432:5432
  snapshot-pgadmin:
    image: dpage/pgadmin4
    container_name: snapshot-pgadmin
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "40"
      PGADMIN_CONFIG_FILE_LOG_LEVEL: "40"
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    depends_on:
      - snapshot-postgres
networks:
    default:
      name: snapshot-network
